all: main.o    getVal.o indiceValide.o InitialiseJeu.o  setVal.o 	Partie1test.o
	gcc -Wall -o main main.o    getVal.o indiceValide.o InitialiseJeu.o  setVal.o Partie1test.o

main.o: main.c
	gcc -c main.c




getVal.o: getVal.c
	gcc -c getVal.c 

indiceValide.o: indiceValide.c
	gcc -c indiceValide.c 

InitialiseJeu.o: InitialiseJeu.c
	gcc -c InitialiseJeu.c 



setVal.o: setVal.c
	gcc -c setVal.c 

Partie1test.o: Partie1test.c
	gcc -c Partie1test.c

