all: main.o    getVal.o InitialiseJeu.o  setVal.o getVal.o 	Partie3test.o ajouteValalea.o indiceValide.o caseVide.o mouvement.o 
	gcc -Wall -o main main.o    getVal.o  InitialiseJeu.o  setVal.o Partie3test.o  ajouteValalea.o indiceValide.o caseVide.o mouvement.o
main.o: main.c
	gcc -c main.c

getVal.o: getVal.c
	gcc -c getVal.c 

InitialiseJeu.o: InitialiseJeu.c
	gcc -c InitialiseJeu.c 


setVal.o: setVal.c
	gcc -c setVal.c 

mouvement.o: mouvement.c
	gcc -c mouvement.c 


Partie3test.o: Partie3test.c
	gcc -c Partie3test.c


caseVide.o : caseVide.c
	gcc -c caseVide.c
indiceValide.o: indiceValide.c
	gcc -c indiceValide.c 

ajouteValalea.o: ajouteValalea.c
	gcc -c ajouteValalea.c
